language: c
os:
    - linux

matrix:
    include:
        - dist: xenial
        - dist: focal

addons:
  apt:
    packages:
     - python3-stdeb
     - python3-setuptools
     - fakeroot 
     - python3-all
     - python-all
     - python3-all-dev
     - libsystemd-dev
     - python3
     - python3-dev 
     - dh-python 
     - fdupes 
     - build-essential 
     - devscripts 
     - debhelper

before_install:
    - sudo add-apt-repository -y ppa:fkrull/deadsnakes
    - sudo apt-get -y update

install:
    - sudo apt-get install python3 python3-dev -y

script:
    - ./build.sh 
