# Only build tags
if: tag IS present

language: c
os:
    - linux

matrix:
    include:
        - dist: xenial
        - dist: focal

cache: apt

addons:
  apt:
    packages:
     - python3-stdeb
     - fakeroot 
     - python3-all-dev
     - libsystemd-dev

script:
    - ./build.sh 
