language: c
os:
    - linux

matrix:
    include:
        - dist: xenial
        - dist: focal

addons:
  apt:
    packages:
     - python3-stdeb
     - fakeroot 
     - python3-all
     - python3-all-dev
     - libsystemd-dev
  
script:
    - ./build.sh 
