# Only build tags
if: tag IS present

language: c
os:
    - linux

matrix:
    include:
        - dist: xenial
        - dist: focal

cache: apt

addons:
  apt:
    packages:
     - python3-stdeb
     - fakeroot 
     - python3-all-dev
     - libsystemd-dev

script: |
    ver="$TRAVIS_TAG"
    export BUILD_BUILDNUMBER="${ver:1}"
    ./build.sh
 
deploy:
    - provider: launchpad
      slug: "~andreantel/pysysdc/+git/main"
      oauth_token: $LP_OAUTH_TOKEN
      oauth_token_secret: $LP_OUATH_TOKEN_SECRET
      on: 
        tags: true
